### ISSUE TITLE
Adafruit_GrayOLED.h: No such file or directory

### ISSUE THREAD

**Issue by raphael303** [adafruit/Adafruit_SSD1327#4]
If I run the Demo I get: 

------------
In file included from /var/folders/33/b5jv16x55xb6hxmdcjwt8l780000gn/T/arduino_modified_sketch_940812/ssd1327_test.ino:1:0:
...PATH.... /Adafruit_SSD1327-master/Adafruit_SSD1327.h:18:10: fatal error: Adafruit_GrayOLED.h: No such file or directory
 #include <Adafruit_GrayOLED.h>
          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
Error compiling for board Arduino Uno.
------------

I have tried uncommenting that line from the library file but then get even more, other errors. Also wire.h is not included, which gives an error.
To me this library does not work at all.

**Comment by ladyada** [comment]
do not uncomment library code, update all  your libraries and IDE

**Comment by raphael303** [comment]
Hi, Yes, I do normally not uncomment library code. It was just an act of desperation.
I can not update to the newest AdafruitGFX because the newest AdafruitGFX library does not display black on the adafruit 2.7 tricolor EPD and I still use this for many projects. So I'm stuck with 1.8 something of the GFX. IDE is 1.8.15, also here, I'm not uptodate because the newer version did not work on BigSur and teensyduino, while this one does. Don't know why. But, well, then that is bad luck for me now.

**Comment by ladyada** [comment]
ok!
