### ISSUE TITLE
How to "display.begin" for SPI displays?

### ISSUE THREAD

**Issue by raphael303** [adafruit/Adafruit_SSD1327#5]
Hi
I have tried to use this for a display hooked up via SPI. I get "Unable to initialize OLED" even though it works with the u8g2 library.

Of course I have adapted all the pins and uncommented the line for I2C, but I can't shake that the "display.begin(0x3D)" is for I2C action and does need to be changed for SPI use...

But how?

**Comment by caternuson** [comment]
Are you using the Adafruit display?
https://www.adafruit.com/product/4741

Did you cut the jumpers to enable SPI mode?
https://learn.adafruit.com/adafruit-grayscale-1-5-128x128-oled-display/pinouts#step-3077235

**Comment by caternuson** [comment]
Closing due to lack of response. Unknown what hardware is being used and in what configuration.
